# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: meta
    hooks:
      - id: check-hooks-apply
      - id: check-useless-excludes

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-json
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: pretty-format-json
      - id: trailing-whitespace

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.35.1
    hooks:
      - id: yamllint

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint

  - repo: local
    hooks:
      - id: hadolint
        name: hadolint
        language: docker_image
        entry: hadolint/hadolint:latest

  - repo: https://github.com/ansible-community/ansible-lint.git
    rev: v24.6.1
    hooks:
      - id: ansible-lint
        always_run: false
